<a href="https://colab.research.google.com/github/RazyAnas/MachineLearning/blob/main/Feature_Construction_Feature_Splitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Feature Construction
manual, no math, domain knowledge and intuition required

depends on data we have

In [43]:
import pandas as pd
import numpy as np

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [44]:
df = pd.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day45-feature-construction-and-feature-splitting/train.csv')[['Age', 'Pclass', 'SibSp','Parch','Survived']]

In [45]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [46]:
# in titanic we can make family using SibSp and Parch

In [47]:
df.isnull().sum()

Age         177
Pclass        0
SibSp         0
Parch         0
Survived      0
dtype: int64

In [48]:
df.dropna(inplace=True)

In [49]:
df.isnull().sum()

Age         0
Pclass      0
SibSp       0
Parch       0
Survived    0
dtype: int64

In [50]:
X = df.iloc[:, 0:4]
y = df.iloc[:, -1]

In [51]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=20))

np.float64(0.6933333333333332)

## Applying Feature Construction

In [52]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1

In [53]:
X['isAlone'] = X['Family_size'].apply(
    lambda num: 1 if num == 0 else (1 if num > 1 and num <= 4 else 2)
)

In [54]:
X.drop(columns=['SibSp', 'Parch', 'Family_size'], inplace=True)

In [55]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=20))

np.float64(0.7326587301587301)

# Feature Splitting

Data not tidy, more than one data in a single cell

In [56]:
df = pd.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day45-feature-construction-and-feature-splitting/train.csv')

In [57]:
df['Name'].sample(20)

288                            Hosono, Mr. Masabumi
353                       Arnold-Franchi, Mr. Josef
572                Flynn, Mr. John Irwin ("Irving")
718                             McEvoy, Mr. Michael
626                  Kirkland, Rev. Charles Leonard
98             Doling, Mrs. John T (Ada Julia Bone)
796                     Leader, Dr. Alice (Farnham)
82                   McDermott, Miss. Brigdet Delia
541            Andersson, Miss. Ingeborg Constanzia
325                        Young, Miss. Marie Grice
837                             Sirota, Mr. Maurice
519                             Pavlovic, Mr. Stefo
596                      Leitch, Miss. Jessie Wills
424                     Rosblom, Mr. Viktor Richard
103                      Johansson, Mr. Gustaf Joel
880    Shelley, Mrs. William (Imanita Parrish Hall)
123                             Webber, Miss. Susan
573                               Kelly, Miss. Mary
457               Kenyon, Mrs. Frederick R (Marion)
358                            McGovern, Miss. Mary
Name: Name, dtype: object

In [58]:
df['Title'] = df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0] #expand=True means: “Split the text into separate columns.”

In [59]:
df['Title']

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: Title, Length: 891, dtype: object

In [60]:
df.groupby('Title')['Survived'].mean().sort_values(ascending=False)

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64

In [61]:
X['Title'] = df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0] #expand=True means: “Split the text into separate columns.”
X = pd.get_dummies(X, columns=['Title'], drop_first=True)

In [62]:
cross_val_score(
    LogisticRegression(max_iter=1000),
    X,
    y,
    scoring='accuracy',
    cv=20
).mean()

np.float64(0.7914285714285716)