<a href="https://colab.research.google.com/github/RazyAnas/MachineLearning/blob/main/Fetching_data_from_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import requests

In [13]:
# df = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]

In [19]:
df = pd.DataFrame()

In [20]:
df

Empty DataFrame
Columns: []
Index: []

In [23]:

dfs = []

for i in range(1, 429):
    response = requests.get(
        f"https://api.themoviedb.org/3/movie/top_rated"
        f"?api_key=8265bd1679663a7ea12ac168da84d2e8"
        f"&language=en-US&page={i}"
    )

    temp_df = pd.DataFrame(response.json()['results'])[
        ['id', 'title', 'overview', 'release_date',
         'popularity', 'vote_average', 'vote_count']
    ]

    dfs.append(temp_df)


df = pd.concat(dfs, ignore_index=True)

In [24]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,425.2006,9.000,788
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,52.0334,8.720,30316
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,39.3318,8.686,22878
3,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,26.7893,8.571,13871
4,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,25.2584,8.568,17410
...,...,...,...,...,...,...,...
8555,864873,Hypnotic,A young woman seeking self-improvement enlists...,2021-10-27,1.7266,6.015,690
8556,70821,Cyberbully,A woman tries to help her teenage daughter whe...,2011-11-10,0.7685,6.000,473
8557,44977,Dhoom 3,"To avenge his father's death, a circus enterta...",2013-12-19,1.6650,6.015,306
8558,13490,Welcome Home Roscoe Jenkins,When a celebrated TV show host returns to his ...,2008-02-08,2.7627,6.015,309
8559,483202,Eli,A boy named Eli with a rare autoimmune disorde...,2019-10-18,2.9557,6.014,1505

In [25]:
df.to_csv('movies.csv')

In [ ]:
# https://holidayapi.com/v1/holidays?key=f947ba25-bf3b-4794-b561-6e02012506e9&country=US&year=2025&pretty

In [ ]:

dfs = []

for i in range(1, 429):
    response = requests.get(
        f"https://holidayapi.com/v1/holidays"
        f"?key=f947ba25-bf3b-4794-b561-6e02012506e9"
        f"&country=IN&year=2025"
    )

    temp_df = pd.DataFrame(response.json()['results'])[
        ['id', 'title', 'overview', 'release_date',
         'popularity', 'vote_average', 'vote_count']
    ]

    dfs.append(temp_df)


df = pd.concat(dfs, ignore_index=True)

In [29]:
response = requests.get('https://0fbf-117-96-147-218.ngrok-free.app/holidays.json', chunk=500)

TypeError: Session.request() got an unexpected keyword argument 'chunk'