<a href="https://colab.research.google.com/github/RazyAnas/MachineLearning/blob/main/Practice_Encodings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import numpy as np
import pandas as pd

In [49]:
df = pd.read_csv(
    '/content/drive/MyDrive/train_.csv',
    usecols=[
        # Ordinal columns
        'ExterQual',
        'KitchenQual',
        'BsmtQual',
        'GarageQual',

        # Nominal columns
        'Neighborhood',
        'MSZoning',
        'SaleCondition',

        # Target column
        'SalePrice'
    ]
)

In [50]:
df.sample(20)

,MSZoning,Neighborhood,ExterQual,BsmtQual,KitchenQual,GarageQual,SaleCondition,SalePrice
873,RL,NAmes,Gd,TA,TA,TA,Normal,133000
266,RL,Gilbert,TA,Gd,TA,TA,Normal,185000
572,RL,Timber,TA,Ex,Gd,TA,Partial,224500
1144,RL,Edwards,TA,Gd,Fa,TA,Normal,80000
1077,RL,NAmes,TA,TA,TA,TA,Abnorml,138800
963,RL,CollgCr,Gd,Ex,Ex,TA,Normal,239000
1230,RL,Sawyer,TA,Gd,TA,TA,Normal,190000
568,RL,SawyerW,Gd,Gd,Gd,Gd,Normal,316600
1407,RL,Mitchel,TA,TA,TA,NaN,Normal,112000
1069,RL,NAmes,TA,TA,Gd,TA,Normal,135000
259,RM,OldTown,TA,NaN,TA,TA,Normal,97000
283,RL,Somerst,Gd,Gd,Gd,TA,Partial,244600
912,RM,BrkSide,TA,TA,TA,TA,Abnorml,88000
173,RL,NAmes,TA,TA,TA,TA,Normal,163000
1047,RL,CollgCr,TA,Gd,TA,TA,Normal,145000
1051,RL,CollgCr,Gd,Gd,Gd,TA,Partial,200141
1068,RM,MeadowV,TA,Gd,TA,TA,Normal,151400
450,RM,OldTown,TA,TA,Gd,Fa,Normal,110000
1303,RL,Somerst,Gd,Gd,Gd,TA,Normal,232000
868,RL,Gilbert,TA,NaN,TA,TA,Normal,169000

In [51]:
df['BsmtQual'].fillna(df['BsmtQual'].mode()[0], inplace=True)
df['GarageQual'].fillna(df['GarageQual'].mode()[0], inplace=True)

/tmp/ipykernel_14126/3230197072.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BsmtQual'].fillna(df['BsmtQual'].mode()[0], inplace=True)
/tmp/ipykernel_14126/3230197072.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GarageQual'].fillna(df['GarageQual'].mode()[0], inplace=True)

In [52]:
df.columns
# MSZoning (Municipal Subdivision Zoning) --> **NOMINAL**
# Type of area where the house is located.
# Examples:
# RL  = Residential Low Density (normal houses)
# RM  = Residential Medium Density (apartments/townhouses)
# FV  = Floating Village Residential
# C   = Commercial area
# This affects house price because some zones are more desirable.

# Neighborhood --> **NOMINAL**
# Specific locality or area name in Ames, Iowa.
# Examples: NAmes, CollgCr, Gilbert, NridgHt.
# Similar to areas like Bandra, Andheri, Powai in Mumbai.
# Location is one of the strongest factors affecting price.

# ExterQual (Exterior Quality)
# Quality of the outside materials of the house.
# Includes walls, bricks, paint, and finishing.
# Values:
# Ex = Excellent
# Gd = Good
# TA = Typical/Average
# Fa = Fair
# Po = Poor

# BsmtQual (Basement Quality)
# Overall quality and height of the basement.
# Basement = room below ground level.
# Uses the same quality scale: Ex > Gd > TA > Fa > Po.
# Missing value (NaN) usually means the house has no basement.

# KitchenQual (Kitchen Quality)
# Quality of the kitchen, including cabinets, countertops, and finish.
# Uses the same quality scale: Ex > Gd > TA > Fa > Po.

# GarageQual (Garage Quality)
# Quality of the garage structure and condition.
# Uses the same quality scale: Ex > Gd > TA > Fa > Po.
# Missing value (NaN) usually means the house has no garage.

# SaleCondition --> **NOMINAL**
# Condition under which the house was sold.
# Examples:
# Normal  = Regular sale
# Abnorml = Abnormal sale (foreclosure, urgent sale, etc.)
# Partial = Newly built house sold before completion
# Sale condition can impact the final price.

# SalePrice --> TARGET
# Final selling price of the house in US dollars.
# This is the target variable that the machine learning model will predict.

Index(['MSZoning', 'Neighborhood', 'ExterQual', 'BsmtQual', 'KitchenQual',
       'GarageQual', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('SalePrice', axis=1), df['SalePrice'], test_size=0.2, random_state=42)

In [54]:
X_train.head(5)

,MSZoning,Neighborhood,ExterQual,BsmtQual,KitchenQual,GarageQual,SaleCondition
254,RL,NAmes,TA,TA,TA,TA,Normal
1066,RL,Gilbert,Gd,Gd,TA,TA,Normal
638,RL,Edwards,TA,Fa,TA,TA,Normal
799,RL,SWISU,TA,Gd,Gd,TA,Normal
380,RL,SWISU,TA,TA,Gd,TA,Normal

In [55]:
X_test.head(5)

,MSZoning,Neighborhood,ExterQual,BsmtQual,KitchenQual,GarageQual,SaleCondition
892,RL,Sawyer,TA,TA,TA,TA,Normal
1105,RL,NoRidge,Gd,Ex,Gd,TA,Normal
413,RM,OldTown,TA,TA,TA,TA,Normal
522,RM,BrkSide,TA,TA,TA,TA,Normal
1036,RL,Timber,Gd,Ex,Ex,TA,Normal

In [56]:
y_train.head(5)

254     145000
1066    178000
638      85000
799     175000
380     127000
Name: SalePrice, dtype: int64

In [57]:
y_test.head(5)

892     154500
1105    325000
413     115000
522     159000
1036    315500
Name: SalePrice, dtype: int64

In [58]:
df.isnull().sum()

MSZoning         0
Neighborhood     0
ExterQual        0
BsmtQual         0
KitchenQual      0
GarageQual       0
SaleCondition    0
SalePrice        0
dtype: int64

In [59]:
from sklearn.preprocessing import OrdinalEncoder

ordinal_cols = ['ExterQual', 'BsmtQual', 'KitchenQual', 'GarageQual']
quality_order = ['Po', 'Fa', 'TA', 'Gd', 'Ex']

# Use the same order for each ordinal column.
oe = OrdinalEncoder(
    categories=[quality_order] * len(ordinal_cols),
    handle_unknown='use_encoded_value',
    unknown_value=-1,
    encoded_missing_value=-1
)

In [60]:
# Learn the mapping:
# Po -> 0
# Fa -> 1
# TA -> 2
# Gd -> 3
# Ex -> 4
oe.fit(X_train[ordinal_cols])

OrdinalEncoder(categories=[['Po', 'Fa', 'TA', 'Gd', 'Ex'],
                           ['Po', 'Fa', 'TA', 'Gd', 'Ex'],
                           ['Po', 'Fa', 'TA', 'Gd', 'Ex'],
                           ['Po', 'Fa', 'TA', 'Gd', 'Ex']],
               encoded_missing_value=-1, handle_unknown='use_encoded_value',
               unknown_value=-1)

In [61]:
# Transform the categories into numbers.
X_train[ordinal_cols] = oe.transform(X_train[ordinal_cols])
X_test[ordinal_cols] = oe.transform(X_test[ordinal_cols])

In [62]:
from sklearn.preprocessing import OneHotEncoder


nominal_cols = ['Neighborhood', 'MSZoning', 'SaleCondition']

ohe = OneHotEncoder(
    handle_unknown='ignore', # Ignore categories in test data not seen during training
    sparse_output=False # Return a regular NumPy array instead of a sparse matrix
)

# Learn all unique categories from the training data
ohe.fit(X_train[nominal_cols])

# Transform categories into one-hot encoded columns
X_train_nominal = ohe.transform(X_train[nominal_cols])
X_test_nominal = ohe.transform(X_test[nominal_cols])

# Optional: View the names of the generated columns
ohe.get_feature_names_out(nominal_cols)

array(['Neighborhood_Blmngtn', 'Neighborhood_Blueste',
       'Neighborhood_BrDale', 'Neighborhood_BrkSide',
       'Neighborhood_ClearCr', 'Neighborhood_CollgCr',
       'Neighborhood_Crawfor', 'Neighborhood_Edwards',
       'Neighborhood_Gilbert', 'Neighborhood_IDOTRR',
       'Neighborhood_MeadowV', 'Neighborhood_Mitchel',
       'Neighborhood_NAmes', 'Neighborhood_NPkVill',
       'Neighborhood_NWAmes', 'Neighborhood_NoRidge',
       'Neighborhood_NridgHt', 'Neighborhood_OldTown',
       'Neighborhood_SWISU', 'Neighborhood_Sawyer',
       'Neighborhood_SawyerW', 'Neighborhood_Somerst',
       'Neighborhood_StoneBr', 'Neighborhood_Timber',
       'Neighborhood_Veenker', 'MSZoning_C (all)', 'MSZoning_FV',
       'MSZoning_RH', 'MSZoning_RL', 'MSZoning_RM',
       'SaleCondition_Abnorml', 'SaleCondition_AdjLand',
       'SaleCondition_Alloca', 'SaleCondition_Family',
       'SaleCondition_Normal', 'SaleCondition_Partial'], dtype=object)

In [69]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

ordinal_cols = ['ExterQual', 'BsmtQual', 'KitchenQual', 'GarageQual']
nominal_cols = ['Neighborhood', 'MSZoning', 'SaleCondition']

numeric_cols = [
    col for col in X_train.columns
    if col not in ordinal_cols + nominal_cols
]

X_train_ord = X_train[ordinal_cols].to_numpy()
X_test_ord = X_test[ordinal_cols].to_numpy()

X_train_num = X_train[numeric_cols].to_numpy()
X_test_num = X_test[numeric_cols].to_numpy()

X_train_final = np.concatenate(
    [X_train_ord, X_train_num, X_train_nominal],
    axis=1
)

X_test_final = np.concatenate(
    [X_test_ord, X_test_num, X_test_nominal],
    axis=1
)

model = LinearRegression()
model.fit(X_train_final, y_train)

y_pred = model.predict(X_test_final)

print("R² Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

R² Score: 0.712383525816437
MAE: 31548.17495733397
RMSE: 46969.26845873738