<a href="https://colab.research.google.com/github/RazyAnas/MachineLearning/blob/main/06_Stats/US_Baby_Names/Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [2]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [44]:
baby_names = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv')

### Step 4. See the first 10 entries

In [5]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [45]:
# deletes Unnamed: 0
del baby_names['Unnamed: 0']

# deletes Ic
del baby_names['Id']

baby_names.head()

      Name  Year Gender State  Count
0     Emma  2004      F    AK     62
1  Madison  2004      F    AK     48
2   Hannah  2004      F    AK     46
3    Grace  2004      F    AK     44
4    Emily  2004      F    AK     41

### Step 6. What year has the highest number of baby names in the dataset?

In [20]:
baby_names.groupby('Year')['Count'].sum().sort_values(ascending=False).index[0]
# instead we can use baby_names.groupby("Year").sum().idxmax()

np.int64(2007)

### Step 7. Is there more male or female names in the dataset?

In [22]:
baby_names.groupby('Gender')['Count'].sum().sort_values(ascending=False).index[0]

'M'

### Step 8. Group the dataset by name and assign to names

In [48]:
baby_names.groupby('Name')['Count'].sum(numeric_only=True).sort_values(ascending=False)

Name
Jacob       242874
Emma        214852
Michael     214405
Ethan       209277
Isabella    204798
             ...
Abigaile         5
Shatha           5
Zykeriah         5
Zunaira          5
Ezel             5
Name: Count, Length: 17632, dtype: int64

### Step 9. How many different names exist in the dataset?

In [50]:
baby_names['Name'].nunique()

17632

### Step 10. What is the name with most occurrences?

In [28]:
baby_names.groupby('Name')['Count'].sum().sort_values(ascending=False).index[0]

'Jacob'

### Step 11. How many different names have the least occurrences?

In [57]:
names = baby_names.groupby('Name').sum()
len(names[names.Count == names.Count.min()])

2578

### Step 12. What is the median name occurrence?

In [53]:
names = baby_names.groupby('Name').sum()
names.Count.median()

49.0

### Step 13. What is the standard deviation of names?

In [52]:
names = baby_names.groupby('Name').sum()
names.Count.std()

11006.069467891111

### Step 14. Get a summary with the mean, min, max, std and quartiles.

In [41]:
baby_names.describe()

         Unnamed: 0            Id          Year         Count
count  1.016395e+06  1.016395e+06  1.016395e+06  1.016395e+06
mean   2.830990e+06  2.830991e+06  2.009053e+03  3.485012e+01
std    1.652476e+06  1.652476e+06  3.138293e+00  9.739735e+01
min    1.134900e+04  1.135000e+04  2.004000e+03  5.000000e+00
25%    1.317326e+06  1.317328e+06  2.006000e+03  7.000000e+00
50%    2.811920e+06  2.811921e+06  2.009000e+03  1.100000e+01
75%    4.242554e+06  4.242556e+06  2.012000e+03  2.600000e+01
max    5.647425e+06  5.647426e+06  2.014000e+03  4.167000e+03